export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCH_ERROR: "PROFILE_DATA_FETCH_ERROR",
    DATA_FETCH_EDITED: "PROFILE_DATA_FETCH_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
  },
};
